services:
  streamlit-app:
    build: .
    container_name: maintenance-control-app
    ports:
      - "8501:8501"
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - DB_HOST=annadb
      - DB_PORT=3306
      - DB_USER=annauser
      - DB_PASSWORD=BootMe!
      - DB_NAME=annadb
    restart: unless-stopped
    networks:
      - anna-network

networks:
  anna-network:
    name: anna-network


